package util

import (
	"strings"
)

// Generated by chatgpt.
// In this updated implementation, the wrapText function creates a lines slice
// of strings instead of a single string. It appends each wrapped line to the
// slice using the append function. Finally, it returns the lines slice.
func WrapText(text string, lineLength int) []string {
	words := strings.Fields(text) // Split the text into individual words
	lines := make([]string, 0)
	currentLine := ""

	for _, word := range words {
		if len(currentLine)+len(word) <= lineLength {
			// If adding the current word to the line does not exceed the line length
			currentLine += word + " "
		} else {
			// Start a new line with the current word
			lines = append(lines, strings.TrimSpace(currentLine))
			currentLine = word + " "
		}
	}

	// Append the remaining line
	if currentLine != "" {
		lines = append(lines, strings.TrimSpace(currentLine))
	}

	return lines
}
